#!/bin/bash

# Quick Setup Script - Run this to initialize any project

echo "🚀 Quick Project Setup"
echo "====================="
echo ""
echo "This script will:"
echo "1. Run /initproject in Claude Code"
echo "2. Set up DevAssist with isolated knowledge base"
echo "3. Create session management commands"
echo "4. Configure terminal logging"
echo ""
echo "To use:"
echo "  1. cd to your project directory"
echo "  2. Run: claude"
echo "  3. Type: /initproject"
echo ""
echo "That's it! Everything else is automatic."
echo ""
echo "After initialization, use:"
echo "  /session-start              - Begin session"
echo "  .devassist/scripts/claude-project.sh - Run with logging"
echo "  /session-checkpoint         - Save progress"  
echo "  /session-end               - End session"
